### ISSUE TITLE
Releases and update for newer actions?

### ISSUE THREAD

**Issue by vsoch** [popperized/spack#7]
Hey spack-github-action maintainers! I'm wondering if it would make sense to:

 - update this for the newer GitHub actions (I think this syntax is deprecated now, but I haven't tried)
 - have proper releases so the user doesn't have to target a branch

I have a use case of wanting to quickly install spack, and this would be perfect for it.

**Comment by vsoch** [comment]
But I'm not sure what the specific use case for the action would be here, because I can easily use a spack container base to have a quick install of spack, e.g.,
```yaml
jobs:
  spack-containerize:
    runs-on: ubuntu-latest
    container:
      image: spack/ubuntu-bionic
      options: --entrypoint /bin/bash
    steps:
      - name: Checkout
        uses: actions/checkout@v2        
      - name: Generate spack package Dockerfile
        run: |
           spack containerize
```
What are the intended use cases for the action?
